// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc-aerospike-kvs.proto

package grpc_aerospike_kvs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KVSRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVSRequest) Reset()         { *m = KVSRequest{} }
func (m *KVSRequest) String() string { return proto.CompactTextString(m) }
func (*KVSRequest) ProtoMessage()    {}
func (*KVSRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_aerospike_kvs_bbaa5539e6033706, []int{0}
}
func (m *KVSRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVSRequest.Unmarshal(m, b)
}
func (m *KVSRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVSRequest.Marshal(b, m, deterministic)
}
func (dst *KVSRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVSRequest.Merge(dst, src)
}
func (m *KVSRequest) XXX_Size() int {
	return xxx_messageInfo_KVSRequest.Size(m)
}
func (m *KVSRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KVSRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KVSRequest proto.InternalMessageInfo

func (m *KVSRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type KVSResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KVSResponse) Reset()         { *m = KVSResponse{} }
func (m *KVSResponse) String() string { return proto.CompactTextString(m) }
func (*KVSResponse) ProtoMessage()    {}
func (*KVSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_aerospike_kvs_bbaa5539e6033706, []int{1}
}
func (m *KVSResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KVSResponse.Unmarshal(m, b)
}
func (m *KVSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KVSResponse.Marshal(b, m, deterministic)
}
func (dst *KVSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KVSResponse.Merge(dst, src)
}
func (m *KVSResponse) XXX_Size() int {
	return xxx_messageInfo_KVSResponse.Size(m)
}
func (m *KVSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KVSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KVSResponse proto.InternalMessageInfo

func (m *KVSResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*KVSRequest)(nil), "grpc_aerospike_kvs.KVSRequest")
	proto.RegisterType((*KVSResponse)(nil), "grpc_aerospike_kvs.KVSResponse")
}

func init() {
	proto.RegisterFile("grpc-aerospike-kvs.proto", fileDescriptor_grpc_aerospike_kvs_bbaa5539e6033706)
}

var fileDescriptor_grpc_aerospike_kvs_bbaa5539e6033706 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x48, 0x2f, 0x2a, 0x48,
	0xd6, 0x4d, 0x4c, 0x2d, 0xca, 0x2f, 0x2e, 0xc8, 0xcc, 0x4e, 0xd5, 0xcd, 0x2e, 0x2b, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x02, 0xc9, 0xc4, 0xc3, 0x65, 0xe2, 0xb3, 0xcb, 0x8a, 0x95,
	0x14, 0xb8, 0xb8, 0xbc, 0xc3, 0x82, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8,
	0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x75,
	0x2e, 0x6e, 0xb0, 0x8a, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4,
	0xe2, 0xe2, 0xc4, 0x74, 0x98, 0x2a, 0x18, 0xd7, 0xc8, 0x9f, 0x8b, 0xd9, 0x3b, 0x2c, 0x58, 0xc8,
	0x83, 0x8b, 0xd9, 0x3d, 0xb5, 0x44, 0x48, 0x4e, 0x0f, 0xd3, 0x36, 0x3d, 0x84, 0x55, 0x52, 0xf2,
	0x38, 0xe5, 0x21, 0x16, 0x29, 0x31, 0x24, 0xb1, 0x81, 0x9d, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0xcf, 0x68, 0xee, 0x6a, 0xd2, 0x00, 0x00, 0x00,
}
